{% set name = "pyodps" %}
{% set version = "0.12.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyodps-{{ version }}.tar.gz
  sha256: 29fc17786c32fa9635f7a91a371e498d4f8719533c30844d0ed907ce4f31d3bf

build:
  entry_points:
    - pyou = odps_scripts.pyou:main
    - pyodps-pack = odps_scripts.pyodps_pack:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.0,<3.1                      # [build_platform != target_platform]
    - numpy >=2.0.0,<2.3.0                   # [build_platform != target_platform]
    - wheel                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - pip
    - setuptools <64  # [py<=311]
    - setuptools <70  # [py>311]
    # yes, wheel is really needed (for python 3.13 at least)
    - wheel
    - numpy >=2.0.0,<2.3.0
    - cython >=3.0,<3.1  # [not win]
  run:
    - python
    - requests >=2.4.0
    - pyarrow >=2.0.0
    - {{ pin_compatible('numpy') }}

test:
  imports:
    # cupid appears to be imported as part of the pyodps[mars] 
    # extra that we're not planning to support
    # - cupid
    - odps
    - odps_scripts
  commands:
    - pip check
    - pyou --help
    - pyodps-pack --help
  requires:
    - pip

about:
  home: http://github.com/aliyun/aliyun-odps-python-sdk
  summary: ODPS Python SDK and data analysis framework
  license: MIT AND Apache-2.0
  license_file: License
  dev_url: http://github.com/aliyun/aliyun-odps-python-sdk

extra:
  recipe-maintainers:
    - xylar
