schema_version: 1

context:
  name: pyodps
  version: 0.13.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pyodps-${{ version }}.tar.gz
  sha256: f1de80ffc9117d4c1b2304f0edf10e2305080779cbaebc6d96e10c583d925e1c

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - pyou = odps_scripts.pyou:main
      - pyodps-pack = odps_scripts.pyodps_pack:main

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - wheel
        - if: match(python, "<=3.12")
          then: cython >=3.0,<3.1
          else: cython >=3.1,<3.3
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
  host:
    - python
    - pip
    - setuptools >=64
    # yes, wheel is really needed (for python 3.13 at least)
    - wheel
    - if: python < "3.13"
      then: numpy >=2.0.0,<2.5.0
      else: numpy >=2.0.0
    - if: unix and python < "3.13"
      then: cython >=3.0,<3.1
    - if: unix and python >= "3.13"
      then: cython >=3.1,<3.3
  run:
    - python
    - requests >=2.8.0
    - pyarrow >=2.0.0
    # from the full extra
    - jupyter >=1.0.0
    - ipython >=4.0.0
    - numpy >=1.6.0
    - pandas >=0.17.0
    - matplotlib-base >=1.4
    - python-graphviz >=0.4
    - greenlet >=0.4.10
    - if: unix
      then: cython >=0.20
tests:
  - python:
      imports:
        - odps
        - odps_scripts
  - requirements:
      run:
        - pip
    script:
      - pip check
      - pyou --help
      - pyodps-pack --help

about:
  summary: ODPS Python SDK and data analysis framework
  license: MIT AND Apache-2.0
  license_file: License
  homepage: http://github.com/aliyun/aliyun-odps-python-sdk
  repository: http://github.com/aliyun/aliyun-odps-python-sdk

extra:
  recipe-maintainers:
    - xylar
